# Generated by Django 5.0 on 2023-12-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_rename_users_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reviews', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
