# Generated by Django 5.0 on 2023-12-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_kitty'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitty',
            name='category',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='kitty',
            name='price',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AddField(
            model_name='kitty',
            name='size',
            field=models.CharField(default='', max_length=200),
        ),
    ]
