# Generated by Django 5.0 on 2023-12-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_remove_kitty_reviews_kitty_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitty',
            name='description',
        ),
        migrations.AddField(
            model_name='kitty',
            name='description1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='kitty',
            name='description2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='kitty',
            name='description3',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='kitty',
            name='description4',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='kitty',
            name='description5',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='kitty',
            name='description6',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='kitty',
            name='description7',
            field=models.CharField(default='', max_length=500),
        ),
    ]
