# Generated by Django 5.0 on 2023-12-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_remove_kitty_description_kitty_description1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitty',
            name='image2',
            field=models.ImageField(default=2, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kitty',
            name='image3',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
