# Generated by Django 5.0 on 2023-12-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('card', models.CharField(default='', max_length=16)),
                ('phonenumber', models.CharField(default='', max_length=200)),
                ('date', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
